# Generated by Django 5.0 on 2024-01-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irpybookapp', '0002_registrolivro'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrolivro',
            name='favorito',
            field=models.BooleanField(default=False),
        ),
    ]
