# Generated by Django 4.2.4 on 2024-01-17 19:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('irpybookapp', '0003_registrolivro_favorito'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registrolivro',
            name='favorito',
        ),
        migrations.AlterField(
            model_name='livro',
            name='data',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='LivroAdicionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irpybookapp.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
