# Generated by Django 4.2.4 on 2024-02-01 03:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('irpybookapp', '0004_remove_registrolivro_favorito_alter_livro_data_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtividadeUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_atividade', models.CharField(max_length=255)),
                ('data_atividade', models.DateTimeField(auto_now_add=True)),
                ('livro_relacionado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='irpybookapp.livro')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
