# Generated by Django 3.2.22 on 2024-02-05 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irpybookapp', '0005_atividadeusuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(max_length=150),
        ),
    ]
