# Generated by Django 3.2.22 on 2024-02-05 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('irpybookapp', '0006_alter_livro_sinopse'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='sinopse',
            field=models.TextField(max_length=350),
        ),
    ]
